#
# Memento
# Docker Compose
# Development Stack
#

version: "3"
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - database-data:/usr/local/pgsql/data
  backend:
    image: mrzzy/memento-backend
    build:
      context: .
      dockerfile: containers/backend/Dockerfile
    ports:
      - "5000:5000"
    env_file: ".env"
    environment:
      - "DATABASE_HOST=postgres:5432"
    depends_on:
      - postgres
  frontend:
    image: mrzzy/memento-frontend
    build:
      context: .
      dockerfile: containers/frontend/Dockerfile
    ports: 
      - "3000:3000"
    env_file: ".env"
    environment:
      - "BACKEND_HOST=backend:5000"
      - "REACT_APP_API_HOST=localhost:5000"
    volumes:
      - "./src/frontend:/frontend:ro"
    depends_on:
      - backend
volumes:
  database-data:
