#
# Memento
# Docker Compose
# Development Stack
#

version: "3"
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    env_file: "src/backend/.env"
    volumes:
      - database-data:/usr/local/pgsql/data
  backend:
    image: mrzzy/memento-backend
    build:
      context: .
      dockerfile: containers/backend/Dockerfile
    ports:
      - "5000:5000"
    env_file: "src/backend/.env"
    depends_on:
      - postgres
  frontend:
    image: mrzzy/memento-frontend
    build:
      context: .
      dockerfile: containers/frontend/Dockerfile
    ports:
      - "3000:3000"
    env_file: "src/frontend/.env"
    volumes:
      - "./src/frontend:/frontend:ro"
volumes:
  database-data:
