#
# Memento
# Docker Compose
# Development Stack
#

version: "3"
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - database-data:/usr/local/pgsql/data
  # memento-backend container
  backend:
    image: mrzzy/memento-backend
    build:
      context: .
      dockerfile: containers/backend/Dockerfile
    ports:
      - "5000:5000"
    env_file: ".env"
    depends_on:
      - postgres
volumes:
  database-data:
