#
# Cnative Course
# Containers
# Docker Compose - Stack
#

version: "3"
services:
  database:
    # TODO: specify image to use as database
    
    # TODO: expose database port
    
    # TODO: configure container environment variables
    
    # TODO: configure storage for database

  backend:
    # TODO: update image name your dockerhub username

    build:
      context: .
      dockerfile: containers/backend/Dockerfile
    # TODO: expose and forward backend port to be externally accesssable
    # <external port>:<container port>
    
    # TODO: configure container environment variables
    # use environment variables direct the frontend to find the database

    # TODO: specify container dependency

  frontend:
    # TODO: update image name your dockerhub username

    build:
      context: .
      dockerfile: containers/frontend/Dockerfile
    # TODO: expose and forward frontend port to be externally accesssable
    # <external port>:<container port>

    # TODO: configure container environment variables
    # use environment variables direct the frontend to find the backend

    # TODO: create a bind mount from /src/frontend to /frontend for hot reload demo
    # NOTE: remove this section when deploying to google cloud

    # TODO: specify container dependency

volumes:
  database-data: {}
